<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grpc.AspNetCore" Version="2.80.0" />
    <PackageReference Include="QuestPDF" Version="2026.7.3" />
    <PackageReference Include="RabbitMQ.Client" Version="7.2.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Shared\VstOnlineStore.Observability\VstOnlineStore.Observability.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="..\..\Contracts\invoiceservice.proto" GrpcServices="Server" Link="Protos\invoiceservice.proto" />
  </ItemGroup>

</Project>
