receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:6687

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 128
    spike_limit_mib: 32
  batch:
    timeout: 1s
    send_batch_size: 256

exporters:
  file:
    path: ./Logs/OpenTelemetry/vst-online-store.jsonl
    format: json
    append: true
    flush_interval: 1s
    create_directory: true

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [file]
