// <auto-generated />
using System;
using System.Text.Json;
using AuditService.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AuditService.Storage.Migrations
{
    [DbContext(typeof(AuditDbContext))]
    partial class AuditDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AuditService.Storage.AuditSnapshotEntity", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor");

                    b.Property<Guid>("CorrelationId")
                        .HasColumnType("uuid")
                        .HasColumnName("correlation_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("event_type");

                    b.Property<JsonElement>("Payload")
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<Guid?>("PreviousEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("previous_event_id");

                    b.Property<string>("ResponsibleService")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("responsible_service");

                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_number");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status_code");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.HasKey("EventId")
                        .HasName("pk_audit_snapshots");

                    b.HasAlternateKey("CorrelationId", "EventId")
                        .HasName("ak_audit_snapshots_correlation_event");

                    b.HasIndex("SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ux_audit_snapshots_sequence_number");

                    b.HasIndex("CorrelationId", "PreviousEventId");

                    b.HasIndex("CorrelationId", "Timestamp", "SequenceNumber")
                        .HasDatabaseName("ix_audit_snapshots_correlation_timeline");

                    b.ToTable("audit_snapshots", null, t =>
                        {
                            t.HasCheckConstraint("ck_audit_snapshots_actor_not_blank", "length(btrim(actor)) > 0");

                            t.HasCheckConstraint("ck_audit_snapshots_responsible_service_not_blank", "length(btrim(responsible_service)) > 0");

                            t.HasCheckConstraint("ck_audit_snapshots_sequence_number_positive", "sequence_number > 0");
                        });
                });

            modelBuilder.Entity("AuditService.Storage.AuditSnapshotEntity", b =>
                {
                    b.HasOne("AuditService.Storage.AuditSnapshotEntity", null)
                        .WithMany()
                        .HasForeignKey("CorrelationId", "PreviousEventId")
                        .HasPrincipalKey("CorrelationId", "EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_audit_snapshots_previous_event");
                });
#pragma warning restore 612, 618
        }
    }
}
