<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Grpc.AspNetCore" Version="2.80.0" />
	</ItemGroup>

	<ItemGroup>
		<Protobuf Include="..\Contracts\storebackend.proto" GrpcServices="Server" Link="Protos\storebackend.proto" />
	</ItemGroup>

	<ItemGroup>
		<Content Update="Data\warehouse-products.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</Content>
	</ItemGroup>

</Project>
