<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <StartupObject>BackendAPITester.MainBackendAPITester</StartupObject>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\StoreBackend\StoreBackend.csproj" />
    <ProjectReference Include="..\Tools\Tools.csproj" />
  </ItemGroup>

</Project>
